apiVersion: apps/v1
kind: Deployment

metadata:
  name: zomato-deploy
  labels:
    app: zomato

spec:
  replicas: 2

  selector:
    matchLabels:
      app: zomato

  template:
    metadata:
      labels:
        app: zomato

    spec:
      containers:
        - name: cont1
          image: nehakrr72/zomato_new:bfa607406d2fb724d7dbfd01635d262aadb265e9
          ports:
            - containerPort: 3000 #we are exposing 3000 n dockerfile.