apiVersion: apps/v1
kind: Deployment

metadata:
  name: zomato-deploy
  labels:
    app: zomato

spec:
  replicas: 2

  selector:
    matchLabels:
      app: zomato

  template:
    metadata:
      labels:
        app: zomato

    spec:
      containers:
        - name: cont1
          image: nehakrr72/zomato_new:bad4d393f21b66f570cfa5ef8b00df434d65b8c6
          ports:
            - containerPort: 3000 #we are exposing 3000 n dockerfile.