apiVersion: apps/v1
kind: Deployment

metadata:
  name: zomato-deploy
  labels:
    app: zomato

spec:
  replicas: 2

  selector:
    matchLabels:
      app: zomato

  template:
    metadata:
      labels:
        app: zomato

    spec:
      containers:
        - name: cont1
          image: nehakrr72/zomato_new:1b3dea63c6a7d30e32105d2fed277dc67bd1a03b
          ports:
            - containerPort: 3000 #we are exposing 3000 n dockerfile.